### PR TITLE
CATransform3D

### PR DESCRIPTION
**Pull request by colinta**
FTW. :smiley:

added `shear` and `perspective` transforms.  I'd like to create some rotation methods that take perspective into account (they would need to know something about how "far away" the view is I think).

### CODE REVIEW

**Comment by colinta** [comment]
oops, i put a fix on a feature branch.  one sec.

**Comment by colinta** [comment]
k, ready!

**Comment by clayallsopp** [comment]
Absurdly cool. Maybe it'd be helpful if there were some pics in the `README` for `shear` and `perspective`?

**Comment by colinta** [comment]
Good call!  Will get on it.  Actually I thought of creating a demo app within geomotion anyway, I could grab them off there.

**Comment by colinta** [comment]
okay, check out the README here: https://github.com/colinta/geomotion/

**Comment by ddrscott** [comment]
​+100

**Comment by clayallsopp** [comment]
Ohhh that is cool :)

**Pull request merged**
